### ISSUE TITLE
Errors during build again 

### ISSUE THREAD

**Issue by katedoctor** [millsp/ts-toolbelt#129]
![image](https://user-images.githubusercontent.com/34662518/87680667-61e27e80-c786-11ea-941f-61d0b8710e3e.png)
The issue https://github.com/millsp/ts-toolbelt/issues/125 **valid again**

**Comment by millsp** [comment]
I think this is a different issue. You need to upgrade to TypeScript 3.7.

**Comment by millsp** [comment]
Please let me know if you still have the same issues after the upgrade.
