### ISSUE TITLE
Was O.Compact deprecated?

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#131]
#### Describe your question
I'm using `O.Compact` in a [merge-anything](github.com/mesqueeb/merge-anything) library of mine. And I wanted to check something in the docs about it, but it seems to have disappeared! :D 

Was it deprecated?

To what should I update the `O.Compact` type for best future proofing?

#### Search tags, topics
#compact #o.compact #deprecated

**Comment by millsp** [comment]
Yes, Compact has indeed been deprecated. It was a confusing utility. There
is MergeAll and PatchAll now that now use Merge and Patch. Where Merge is
the old MergeUp with a lot of rework and Patch is the old Merge.
At the same time, all the "Up" utilities have been deprecated too.

**Comment by mesqueeb** [comment]
@millsp this definitely seems like the good thing to do!

Can you let me know how I best write this signature according to the newer syntax?

```ts
<T extends object, Tn extends object[]>(origin: T, ...newComers: Tn): O.Compact<T, Tn, 'deep'>
```

And feel free to close the issue as well ;)
