### ISSUE TITLE
O.Compact broken in 6.13

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#132]
## 🐞 Bug Report

```ts
import { O } from 'ts-toolbelt'

export enum ACTIVE_LESSON_STUDENT_STATUS {
	NEEDS_HELP = "NEEDS_HELP",
}

export interface StudentMeta {
	statuses: ACTIVE_LESSON_STUDENT_STATUS[]
}

type MergedWithCompact = O.Compact<StudentMeta, [Partial<StudentMeta>], 'deep'>

// v6.12 ✅
// type MergedWithCompact = {
// 	statuses: ACTIVE_LESSON_STUDENT_STATUS[];
// }

// v6.13 ❌
// type MergedWithCompact = {
// 	statuses: {
// 			[x: number]: ACTIVE_LESSON_STUDENT_STATUS;
// 	};
// }
```

The 0.13 is breaking a lot of things in my libraries with ts-toolbelt as depedency.

Right now my solution is to hard-code the version to v0.12 in all my libraries & tools that use ts-toolbelt.

**Comment by millsp** [comment]
Looking into this

**Comment by millsp** [comment]
This is happening because the new `Merge` is able to merge lists too, the old one would just skip it. This was a huge issue for type safety. And the problem here is that I chose to set the merging default to ramda style, that means that lists are not preserved by default...

So if you enable lodash-merging style, you can do pretty amazing things!

```ts
type t0 = Merge<{
    a: number[]
    b: {a: 1}[]
    c: {a: [0]}
}, {
    a: string[]
    b: {b: 2}[]
    c: {a: [0, 1, 2]}
}, 'deep', 0>

// {
//     a: (string | number)[];
//     b: {
//         a: 1;
//         b: 2;
//     }[];
//     c: {
//         a: [0, 1, 2];
//     };
// }
```

Actually, I plan to make the lodash-merging style the default soon.

**Comment by mesqueeb** [comment]
@millsp
I'm all for positive change and increasing possibilities!

However, as you've seen from my continuous struggles, a behaviour change we've seen with 6.13 _does_ force people to update the ts-toolbelt syntax in various parts of their apps. So because the syntax needs changing, I'd consider this a breaking change.
What's your thought on reverting to 6.12 behaviour and releasing 6.17 as v7.0?

**Comment by millsp** [comment]
You just have to pass the `0` option like in the example.

**Comment by millsp** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46213

**Comment by millsp** [comment]
The only thing to know when using lodash merging style is that when one of your fields is `undefined`, lodash will fill that gap when merging, that's not the case for ramda. Ramda instead checks if the key exists or not. So if you have a field that you explicitly set to `undefined`, ramda wont complete it while merging.

**Comment by millsp** [comment]
Fixed!
