### ISSUE TITLE
Unused declaration in `Iteration/Format` cause TS build error

### ISSUE THREAD

**Issue by selfrefactor** [millsp/ts-toolbelt#133]
#### Describe the bug

The original issue is https://github.com/selfrefactor/rambda/issues/511

I am using `ts-toolbelt` but I ship part of its code within my library, so users receive full TS support out-of-the-box. The unused part `IMap extends Map = NumberMap` causes TS build error with following TS config:

```
"compilerOptions": {
        "noUnusedLocals": true,
        "noUnusedParameters": true
 },
```

#### Reproduce the bug

Repo: https://github.com/selfrefactor/rambda-tree-shaking

Folder: `packages/rambda`

Command: `yarn build`

#### Expected behavior

Build process completes with no errors.

#### Possible Solution

Remove the unused code.

**Comment by millsp** [comment]
Thanks for reporting this @selfrefactor. It's fixed!

**Comment by selfrefactor** [comment]
So again, there are unused variables that causes problems for me. Is there a way to add such check, so I don't have to trouble you every time?

**Comment by millsp** [comment]
no stale

**Comment by millsp** [comment]
not stale!
