### ISSUE TITLE
O.Optional removes non optional properties

### ISSUE THREAD

**Issue by xaviergonz** [millsp/ts-toolbelt#135]
I think this is something new since the latest version

```ts
type AAA = O.Optional<
{
  values: number[],
  optValues: number[]
},
"optValues"
>
```
this only yields `optValues?: number[] | undefined;` and removes `values`

**Comment by millsp** [comment]
Thank you, I'm looking into it.

**Comment by millsp** [comment]
And another bug is gone, thank you!
