### ISSUE TITLE
O.Optional key param has changed, using `any` breaks the type

### ISSUE THREAD

**Issue by tonivj5** [millsp/ts-toolbelt#137]
#### Describe the bug
In `6.13.36` this type worked right using `any` as `Key` param, now it doesn't

#### Reproduce the bug
```ts
type Test = O.Optional<{ test: { subtest: string } }, any, 'deep'>;
const test: Test = null;
// test has this type
// const test: {
//   [x: string]: OptionalDeep<any>;
// }
```

#### Expected behavior
Expected type (as in `6.13.36`):
```ts
const test: {
    test?: OptionalDeep<{
        subtest: string;
    }>;
}
```

#### Possible Solution
Using `A.Key` as `Key` param works :+1:
```ts
type Test = O.Optional<{ test: { subtest: string } }, A.Key, 'deep'>;
```

#### Additional context
I'm using latest typescript version (`3.9.7`).

This worked before, but maybe this is the expected behavior :sweat_smile:

**Comment by millsp** [comment]
Hey @tonivj5, thanks for reporting this, I know. The reason that this was working before is a bug that I corrected. This now behaves like any other mapped type should. Sorry about this! And yes, you should always use `A.Key`:

```ts
type t0 = Pick<{a: 1, b: 2}, any> // {[x: string]: any}
```

Cheers!
