### ISSUE TITLE
can ts-toolbelt be used to replace manual overloads for string object path getters like lodash get

### ISSUE THREAD

**Issue by dagda1** [millsp/ts-toolbelt#138]
#### Describe your question
I have created [this playground](https://www.typescriptlang.org/play#code/KYDwDg9gTgLgBDAnmYcBCBXAdgEwDbBQCiUU0cAvHAN5wC2wAzowIYDmwAXHIzFAJZY2cAL4BuAFChIsBMlSZcBKAHUWULIOFVaDZuy48+W0ZKnho8JCnTZ8hEmSiNKNOISeNui+8VLQAbQBdMTgAd3VNIS9bJUI1DS1g0QlzGSt5WN8AZRgWGFQKCTg4AB83XnyMGIBybAAjOwIcGpSS8tpKmGruGsb+PBwtVpFisoq87tq2KGBgLBrQsHyAC25eASFROAAyOAAFfgBjAGsAHh9lR2hGABo4GojE6JqAPjGOoyraj2hgFu2e0uDn8zg+E2+vQwYBw+X+izgyxgayMm2E4lSggKUAAZiwjqgAHIQHCoahjUmMI4CMAwfgQLDrYxCSSjCTWVAAWRYmhxTHgOgpTGp-Fp9MZqK0tzGOIGwEJLAYTLR0pKvGAYBixNJwQkbI5cFycNc5JKjTiUG8TUIRoKkhKdB5-D5vG43N5-NZqWkljgRzwLGYhrwx2AZwAKvdsq8aGMjgyNhgjjBoAAKMACABuxvyEDo3AAgim6Gdo-cwBh6iGjojVoXSCxEGcNiZylgMHR6oRXgBKWMlNlq6thgDSwEQ7hABVwLhO44gOLg4deqbniG4Y8QPe42WHEYCm6CUde9p4e83AEZJ9OcLP54vI3BNwAma-zW9wNcLpcH8cXoIrmuF4bn+9xrs+IGIM+27BqG+6XkEv5QUehonmMjDnn+b4zp+95LvcL7YR+X4Pkh-4EeOADMRF3og37hmRiEvgBq5-pBF5geOEFPlxnGIJRkGUTBu5wQxCFIc+TFUSh0anhhcGXjRuF0Q+FFQUpJE-ghanUaAN60fRjESShm4ACwaXhYl-lJyFIZRLFAexfHcS+fECTx-F8aZkGmcJe5WYg-7GXZNmmTJaFDgpWF6e+BmqR5r4xThmkBeRHm6VOsXKYZ4nMWp5lJcRllGcxIVqQArBZKladZwWbvZSFhYBbEeRxykubxynufVXk+Xx5WQeVfmiSVXE2Q1Zk2eV4VyZhgVVfRamJZlyXFdp6ULaRuVjflm01YFNmSWVHmVYVcX7UFpX1aFJnjgAbHtqWHeNN1IdNzWBU57WQc+bmCb1Hmmf1g18ZBd3DQS8G1Vd0mNVNNl3TN6FzVeZ3ZfFhFoyljE6Y9o3IbtWNrdDY3HZup0rUV1VPXVsOTWpD1E9T+NHddcNvbdiAAOx49ttls5NHNIYjH3Aa1zk-X96UA2ZwMnaDHl3XxXOQVzENhjTMP8a95MIzZXNI5FkOKUzi0Jbz1m46bW0kwTgMWwdtPaxVDuXaTAvjmFDOu89IXs7rak89bF2+x7iBhULm6I2pAAcPtOxNnvw8L+sOS1l4SwlUs9cp3mA3L5MK1Hyuq3xMeQTH6tQ47WuJ+HydR6nSEx4bZ6humdZwAWDZNi2Wxth2XZQL2O7+fcPKIDGpolHAszdBocBYMAYSwQSqbIvwjAAHS5nQ9wb9vSIrFv8ZYEc+Qd8iPY9qeoxsj6sj+oGLhFnmpYxv2foJnwSYplA6ZZmNIIfgdIWB4B3H2aeowSipCNqOcce1oysXXB5Ku2QkKt3ksbaKlNzrZCWogxiosvrgR+mglmmCUaIIIcHdB616qEL5pJYh4tvpZy6oJchTCXrHlmlFeatCaG4PRoaHGG1aEUMJsIzSdDbas2kiwjObDXIcOlrnHyXC5EvThrw5G-DUbSLwvg82Ej6FUUYVoqR+kRGyJru7aSLtTFaL9pNRRoFlGdTXN1KiMtPYF3HENUecFbFu35nTJOHNdFwLOCbQx1VjGYzid+EJnMMrWJkZI+2Ti7FhOdidCxOT5Hax0YrApoSil1wjrrNxgVM4qK8f9dR+dlIDXlspO6YNNGFO0YLXWKcolt2wQIpJi4ElcTKakiZxkrFZQydwsmASpm1xut7bJ5SekRIDh5IOIzRHzLDlUgJesaltVIewhpai1x51li0kG7SwYl22V09ZLjNlHJTkhA2AysHwOGekoxQj-nxLEQwtZz0ZmrWBfshx+SwUJxWaUuFyz-ZHMDks+xxTenvMbrHdFuTKkN3uqnE5dTPFUUaVcvqty2lrg6YrR5m4uZlwrs80O4T66RyJZ8myLdvnDlTFvQVa4Yh9zYMEGCE9p4lDnhgBeS8V4iTXgfPijAb5jDvqkAg8Bd6uHlV3YspZJjABXNPR0HpXSfxKJSEUYoGTcAAETEiXva1UM9ZQEAVEqOA9qzjAJgK8F1Yw1QFE1NwAIQaZ60GtTSOkdqHjqjACMCNR51WuvNL4bgUqvhTChFgdNzQaipr1GqiQp9eBwHzYQVwu8t4-NTH0a0UAag3xKAAelbavMMwIoC2mAFGI17wy3wATS4KgNa601DNc6fkNR7g1BHc20I7bO1nG1MAYI-a4SDu-nAa11biy1v5ZOp0LoYCzvjSGxg56AAMc7o2iljQsFty7FVhlFZugo7xS07vqCwHAaAICIG7fuvMh724NriIuttHbu5sA7PMeA34DQ1HtZW+1rRN6LwgNq5g-A2BYBYFWVAKZaxQEVMAbEcAkOZBQ5WqA9rxj2qnae9DW9UhAA) that shows what I want to achieve and my current sledgehammer solution.

A bit like loash get, I want to retrieve nested properties of an object using string segments like this. 

```typescript
const bundler = atom.slice('bundler');  // Slice<BundlerState, State>
const steps = atom.slice('manifest', 'steps'); // Slice<Node[], State>
const desc = atom.slice('manifest', 'steps', 0, 'description'); // Slice<string, State>
```

The types are inferred as long as I have the correct overload in place and there are probably edge cases that I am missing.

Could I refactor this to use `Object.path` without providing type arguments?  

The inference is important here.

#### Search tags, topics
#typescript #path

**Comment by millsp** [comment]
Yes, we can do exactly what you want, you'll need to combine `PathValid` that will send the warnings on wrong paths, and `Path` to go fetch the type that that validated path:

```ts
class Atom<S extends object> {
    constructor(public s: S) {}
    slice<Keys extends A.Key[]>(...keys: A.Cast<Keys, O.PathValid<S, Keys>>): O.Path<S, Keys> {
        return undefined as any // just for the example
    }
}

export type BundlerError = { message: string };
export type BundlerWarning = { message: string };

export type BundlerErrors = { errors: BundlerError[]; warnings: BundlerWarning[] }

export type BundlerState =
  | { status: 'unbundled' }
  | { status: 'building' }
  | { status: 'green'; path: string } & Pick<BundlerErrors, 'warnings'>
  | { status: 'errored' } & BundlerErrors
  | { status: 'updated'; path: string };

interface Node {
  description: string;
}

type Manifest = {
  description: string,
  fileName: string,
  steps: Node[]
}

type State = {
  bundler: BundlerState;
  manifest: Manifest;
}

const atom = new Atom<State>({
    manifest: {
        description: 'None',
        fileName   : '<init>',
        steps      : [
            {description: 'step'},
        ],
    },
    bundler: {
        status: 'unbundled',
    },
})

const bundler = atom.slice('bundler')  // Slice<BundlerState, State>
const steps = atom.slice('manifest', 'steps') // Slice<Node[], State>
const desc = atom.slice('manifest', 'steps', 0, 'description') // Slice<string, State>

const badBoyBundler = atom.slice('bundle')  // Argument of type '"bundle"' is not assignable to parameter of type '"bundler" | "manifest"'.
```

We `Cast` `Keys` to be `PathValid` to force back-validation of the input, just a little trick.

Does it work for you?

**Comment by dagda1** [comment]
@millsp thank you for the answer and is impressive.

I have created this [codesandbox](https://codesandbox.io/s/friendly-bardeen-eu9xh?file=/src/index.ts)

it does not appear to be picking up the type error for `badBoyBundler` on line 68.

**Comment by millsp** [comment]
It works, this is not the first time codesandbox does this

![Screenshot from 2020-08-09 02-13-26](https://user-images.githubusercontent.com/18401805/89722121-fb97f700-d9e5-11ea-985e-da8e7783f83b.png)

**Comment by eranimo** [comment]
This doesn't work on the latest version. Was `O.PathValid` removed?

**Comment by millsp** [comment]
It has been renamed to `ValidPath`
