### ISSUE TITLE
Support for TypeScript 4.0

### ISSUE THREAD

**Issue by millsp** [millsp/ts-toolbelt#140]
You can now enjoy the most optimized version of ts-toolbelt. Besides countless internal optimizations, the TypeScript team has been working on many ways to improve the type system. This has led to some of the most exciting and awaited features:
- [Variadic Tuple Types](https://github.com/microsoft/TypeScript/pull/39094)
 This means a lot of optimization for this library, not having to emulate `Concat` anymore.
- [Recursive Type Aliases](https://github.com/microsoft/TypeScript/pull/40002)
 We pushed hard for the use of recursive types. I'm very happy to announce that this is officially supported now.
- The TypeScript team has also been working relentlessly on improving performance. And this is something that we can clearly feel on this latest release -- Cutting the type count by 60% for the ts-toolbelt!

Besides that, there will be breaking changes on this version:
- `MergeUp` is now called `Merge`
- `Merge` is now called `Patch`
- Some API's have changed, not very used ones though.

> Why `ts-toolbelt@8` instead of `7`? I only like odd numbers! No. Just a bug with the automated versioning... Not worth my time.

**Comment by mesqueeb** [comment]
nice!!!
