### ISSUE TITLE
Request for advice upgrading post 6.12

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#143]
#### Describe your question

I'm wondering if it's possible to make the types of O.Compact/O.MergeAll more beautiful in VSCode...

Ever since 6.12 + things kind changed a lot.

### 6.12

very beautiful:

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3253920/92981630-a9129480-f4d5-11ea-9968-2c91d861147d.png">

### 6.15.5

<img width="820" alt="image" src="https://user-images.githubusercontent.com/3253920/92981596-79fc2300-f4d5-11ea-9b31-c9ff11feb78a.png">

### latest 8.x

`O.Compact` was not deprecated in the source code, but is the same as 6.15.5:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3253920/92981871-b8461200-f4d6-11ea-81ba-386d533dadc4.png">

Instead you suggested me to use `O.MergeAll` instead:
<img width="847" alt="image" src="https://user-images.githubusercontent.com/3253920/92981902-df9cdf00-f4d6-11ea-994d-bab054915ede.png">

I would like your general advice on my library [merge-anything](https://github.com/mesqueeb/merge-anything) which merges objects and did so with beautiful typing support (until 6.12).

1. I'm not sure if I should force ts-toolbelt 6.12 or not and wanted to ask your general advice.

2. If I do go for v8.x, should I do this as a "major" update?

3. If I go with MergeAll, what should I tell my users in the release note about the new returned type of my merge function?

#### Search tags, topics
#_6.12 #upgrade #compact #mergeall

**Comment by millsp** [comment]
Hey @mesqueeb I think that you should `Patch`. Thanks for letting me know, I will deprecate `Compact`.

**Comment by millsp** [comment]
Actually I'm seeing that none of the deprecated things have been removed :exploding_head:...

**Comment by millsp** [comment]
So this is what changed (on the left <= v6, on the right > v6):

`Merge`   -> `Patch`
`MergeUp` -> `Merge`
`Compact` -> `PatchAll`

So you should use `PatchAll`. I can't remember why but you couldn't use `MergeAll` (which would have the best type safety), I think that you had something like `{[K: string]: any}` that prevented that.

The reason behind the renaming of the tools is that `Merge` on the v6 merged without handling unions and optional fields - not like a JS merging. In the meantime `MergeUp` got so efficient overtime that I decided that this was actually THE real merge. But maybe people did not wan't a merge that handles optional fields, after all? Then from that, I created `Patch`, that is exactly like `Merge` (v8) but it does not handle optional fields - it patches if the fields don't exist.

**Comment by mesqueeb** [comment]
@millsp
Unfortunately, I just checked and it's the same for PatchAll.
I'm talking about how these types look in VSCode pop up.

O.Compact v6.12 is only way to show a merged type way more beautiful as-is without anything the dev might not understand. See difference:

### O.PatchAll

<img width="841" alt="image" src="https://user-images.githubusercontent.com/3253920/93028252-80150f80-f64d-11ea-8b29-3f637822d600.png">

### Vs. O.Compact pre 6.12

<img width="822" alt="image" src="https://user-images.githubusercontent.com/3253920/93028265-915e1c00-f64d-11ea-8a0a-24c7977779fe.png">

So as you can see, this part looks weird and might confuse devs:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/3253920/93028287-daae6b80-f64d-11ea-9376-c51f6f049fe0.png">
While this same part with v6.12 was beautiful:
<img width="454" alt="image" src="https://user-images.githubusercontent.com/3253920/93028294-eac64b00-f64d-11ea-8d20-efd464dd64c2.png">

**Comment by millsp** [comment]
Ok, that's just a display problem. In short, this is for handling circular references. If you explicitly want to display it neatly, you should combine it with `Compute`. I'll see in the future what I can do to improve this without introducing performance drops.

```ts
const starter = { name: 'Squirtle', types: { water: true } };
const newvals = { name: 'Wartortle', types: { fight: true }, level: 16 };

type t = A.Compute<O.PatchAll<{}, [typeof starter, typeof newvals], 'deep'>>;
```

**Comment by mesqueeb** [comment]
Hey @millsp I have made the edits as per your advice. And it seemed like everything worked for me with beautiful types.

However, upon build now I got an error:
```
  Uncaught exception in test/mergeAndConcat.ts

  test/mergeAndConcat.ts(14,3): error TS2589: Type instantiation is excessively deep and possibly infinite.

  Uncaught exception in test/index.ts

  test/index.ts(22,3): error TS2589: Type instantiation is excessively deep and possibly infinite.
```

This is what my code looks like with your suggestion integrated as return type:

<img width="723" alt="image" src="https://user-images.githubusercontent.com/3253920/93075335-9b6d3280-f6c0-11ea-94c3-f159126ab0e6.png">

Do you have any advice for me?

**Comment by mesqueeb** [comment]
**idea**: provide a version of PatchAll / MergeAll that does _not_ work with circular references?

my library doesn't support merging objects with circular references anyway, so I'd greatly appreciate the performance boost from a PatchAll / MergeAll that also doesn't  (if there is a performance penalty that is )  : D

and it will probably fix this issue as well.

**Comment by millsp** [comment]
I cloned your repo and the tests are passing. Maybe you should nuke your `node_modules`. And upgrade to ts ^4

**Comment by mesqueeb** [comment]
@millsp I just tried updating all dependencies, but no luck.
Maybe I forgot to mention but: the issue is on the `production` branch. It's not the default branch. 😅 

<img width="787" alt="image" src="https://user-images.githubusercontent.com/3253920/93100407-1431b600-f6e4-11ea-86e2-10677ccaa9a8.png">

**Comment by millsp** [comment]
Got a fix on the way!

**Comment by millsp** [comment]
You cam just use it without `A.Compute` now. Let me know if it works for you.

**Comment by millsp** [comment]
@mesqueeb did it solve your problem?

**Comment by millsp** [comment]
Actually, it could be nice if you can hold on. I'm planning to release a more generic version of `Merge` and `Patch` that will handle arrays and tuples perfectly.

**Comment by mesqueeb** [comment]
@millsp I'm sorry I didn't check this thread past two days!

all problems are solved since `v8.0.6`
I don't even need the A.Compute any more, it shows beautifully by default.

PatchAll, MergeAll both work.

I ended up going for `O.Assign` because I realised that that's the correct one for me now!

**Comment by mesqueeb** [comment]
@millsp PS, I'm happy to test anything else for you, I don't do array or tuple merging in any of my libraries though!
But let me know how I can help! : )

**Comment by millsp** [comment]
ts-toolbelt@9 will be out in November, it will have breaking changes on `Merge` and `Patch`.
