### ISSUE TITLE
TS1256 & TS2574: A rest element type must be an array type.

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#146]
#### Describe the bug

I upgraded a package of mine `merge-anything` to latest version of `ts-toolbelt`, but ever since then I cannot build some projects any more that use `merge-anything`.

Here is the error I'm seeing:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/3253920/93555710-bd610080-f9b1-11ea-9ae6-a47b60e20c42.png">

When I follow the error line, it usually points to usage of `...L` in your library.

<img width="440" alt="image" src="https://user-images.githubusercontent.com/3253920/93555758-e41f3700-f9b1-11ea-96db-c428ae0a8700.png">

#### Reproduce the bug

You can clone `cycraft/blitzar` then do `npm run dep:install` and `lerna exec "build"`

#### Expected behavior
No error

#### Possible Solution
I'm not sure :D 

#### Screenshots
See above

#### Additional context
Here is the package.json of `merge-anything`:
https://github.com/mesqueeb/merge-anything/blob/production/package.json#L49

**Comment by millsp** [comment]
I think that `typescript@4` has not been explicitly set

**Comment by mesqueeb** [comment]
I see! So, if my project is TS 3, and I want to use `merge-anything` which has the latest ts-toolbelt, which needs TS 4, then as result, my project will also be forced to use TS 4! :O I get it now.

**Comment by millsp** [comment]
It's hard to put `typescript` as a peer dependency - something most people don't want
