### ISSUE TITLE
Typescript 3.8 compatibility.

### ISSUE THREAD

**Issue by KpjComp** [millsp/ts-toolbelt#151]
## 🐞 Bug Report

Doc's say that Typescript 3.5+ is supported, but it looks like Typescript 4.0 is now only supported.

#### Reproduce the bug

I've extracted the relevant part of the .d.ts file for simplicity.

```ts
type List<A = any> = ReadonlyArray<A>;
type Tail<L extends List> = L extends readonly [any, ...infer LTail] ? LTail : L;
```

Here is a playgound to test the versions -> https://www.typescriptlang.org/play?declaration=false&target=2&jsx=0&module=1&ts=3.9.7#code/C4TwDgpgBAMglgZ2AHgIJQLxQIYDsQB8mUAShNgCYD2uANiKgE6PYhoEDcAUKJFACrY4tZDCgQAHsAi4KCWImBEsYydNnzG5anRBQA2nhAAaKADoLcXADMIjWIOEBdKAH4HQ2lABcsbkA

#### Expected behavior
Running the above, you will get an error -> A rest element type must be an array type.
Upping the version in playground to 4, the error goes away.

#### Possible Solution
Either make compatible with 3.5+, or alter docs to say only 4.0+ now supported.

**Comment by millsp** [comment]
Sorry about this. I'll update soon. Here's the compatibility table https://github.com/millsp/ts-toolbelt#-compatibility

**Comment by KpjComp** [comment]
@millsp   Ah, sorry.  My bad.  Didn't notice that compatibility table.

I very rarely worry about versioning, `npm install pkg`, but having `npm install pkg@x.x.x` makes total sense here to get the latest TS features,  I only recently installed so of course got the latest, but at this point hadn't yet updated TS..

**Comment by millsp** [comment]
Actually, I see that there was a link for the support table.
So there's no problem. So I am going to be close this issue.

Don't hesitate to ask any questions related to this lib or TypeScript.

I'm always here to help. Cheers!
