### ISSUE TITLE
How to construct type for "Object having path P"?

### ISSUE THREAD

**Issue by cjol** [millsp/ts-toolbelt#159]
## 🤔 Question

I'm trying to write a curried "select" function which plucks a value from inside a given object. The type for the non-curried version looks like this: 
```ts
declare const selectPlain: <T extends object, P extends Array<A.Key>>(
  item: T,
  ...path: P
) => O.Path<T, P>;
const strVal = selectPlain({ a: { b: '' } }, 'a', 'b');
```

For the curried version, the best I've come up with is this:
```ts
declare const selectCurried: <P extends Array<A.Key>>(
  ...path: P
) => <T extends object>(item: T) => O.Path<T, P>;
const selectFooBar = selectCurried('foo', 'bar');
```
What I don't like about this is the `T extends object` generic. Because of this `selectFooBar` will appear to accept any object. I really want to end up with
```ts
const selectFooBar : <T extends {foo: {bar: any}}>(item: T) => O.Path<T, P>;
```
To do that I think I need to construct the type `{foo: {bar: any}}` from `["foo", "bar"]`. Is that possible?

#### Search tags, topics
#typescript #path #get #select #curry

**Comment by millsp** [comment]
Hey @cjol, yes this is very easy to achieve. We have `Object.P` modules that allow operating on objects at a `Path`. So you are looking for `Object.P.Record` https://millsp.github.io/ts-toolbelt/modules/_object_p_record_.html

**Comment by cjol** [comment]
Thanks, I was sure there would be a solution! For completeness, here is my final solution:

```ts

declare const selectCurried: <P extends Array<A.Key>>(
  ...path: P
) => <T extends O.P.Record<P, any>>(item: T) => O.Path<T, P>;
const selectFooBar = selectCurried('foo', 'bar');
const str = selectFooBar({ foo: { bar: 'hello' } });
// @ts-expect-error
const innerVal = selectFooBar({});

```

**Comment by millsp** [comment]
Glad I could help, have a nice day.
