### ISSUE TITLE
New `String` methods for TS 4.1+

### ISSUE THREAD

**Issue by mikeplus64** [millsp/ts-toolbelt#162]
Now that string templating is possible it's possible to build your own type-level parsers and formatters. Here's what I'd suggest as a start:

```typescript
type Intersperse<L extends List<string|number|bigint>, Sep extends string|number|bigint> = ...

type Split<L extends List<string|number|bigint>, Sep extends string|number|bigint> = ...

type Concat<L extends List<string|number|bigint> = ...

type StartsWith<S extends string, Prefix extends string> = ...

type EndsWith<S extends string, Suffix extends string> = ...
```

## Motivation

Writing a type-safe routing library, these are utility types that I've mostly already defined.

**Comment by millsp** [comment]
Hey @mikeplus64, thanks! We should definitely add this. Would you like to open a PR?

**Comment by mikeplus64** [comment]
Yep can do next week some time.

**Comment by janstudeny** [comment]
Hi guys,

would you consider support of object keys case transformation to `*Case` types (like `SnakeCase`, `CamelCase`, `DashCase` etc.)?

Another library called _type-fest_ [already supports](https://github.com/sindresorhus/type-fest#template-literal-types) these types. Also, [here](https://stackoverflow.com/a/65015868) is trivial implementation of `SnakeCase` to `CamelCase` scenario, although I am not qualified to check correctness of the implementation, which seems to be surprisingly simple. 

There are many use cases for this kind of feature, for example when handling difference of object keys case between front-end and back-end apps, where you usually struggling with camel-case to snake-case transformations and vice versa in request/response payloads

By the way, I was wondering if there is library transforming object keys case at runtime and I found this one - [change-case](https://github.com/blakeembrey/change-case). Although I didn't use it yet, it may offers simple solution to described problem in combinations with proposed `*Case` types.
