### ISSUE TITLE
Support for `Any.If` type

### ISSUE THREAD

**Issue by ThomasAribart** [millsp/ts-toolbelt#169]
#### Is your feature request related to a problem?
I haven't seen a `If` tool, which would prove quite useful for many type computations.

#### Describe the solution you'd like
```
type If<Condition extends B.Boolean, Then, Else = B.False> = Condition extends B.True ? B.True extends Condition ? Then : Else : Else;
```

#### Describe alternatives you've considered
Somthing chained like `If<Condition>.Then<Then>.Else<Else>` but I'm not sure that's doable.

#### Teachability, Documentation, Adoption, Migration Strategy
This would be a quite simple feature.

**Comment by millsp** [comment]
Nice idea, I will add it in the next release :)

**Comment by ThomasAribart** [comment]
Nice ! I can open a PR if you want 👍

**Comment by ThomasAribart** [comment]
After experimenting a bit, it would be more natural if `Else` has `never` as a default value.

Besides, it would be a KILLER FEATURE if it can keep the type casted by the check, but I'm not sure it can be done:
```typescript
type U = A | B;
type OperateOnA<a extends A> = ...
type TransformU<u extends U> = u extends A ? OperateOnA<u> : u; // <= work 🙌
type TransformU2<u extends U> = If<A.Extends<u, A>, OperateOnA<u>, u>; // <= Right now, type context is lost so error is lost...
```
