### ISSUE TITLE
Split and join types

### ISSUE THREAD

**Issue by navanshu** [millsp/ts-toolbelt#171]
#### Is your feature request related to a problem?
I really want a type which can iterate over array and send the output as optional, I tried making it but failed.

#### Describe the solution you'd like
```typescript
import { N } from 'ts-toolbelt';
// I want to generate types like --> 1-2 | 2-3 | 3-4 ....

type addOne<K extends string> = `${K}-${N.Plus<K, '1'>}`;
// just for illustration
type estimateTime = addOne<"1"> |
        addOne<"2"> | addOne<"3"> |
        addOne<"4"> | addOne<"5"> |
        addOne<"6"> | addOne<"7"> |
        addOne<"8"> | addOne<"9"> |
        addOne<"10"> | addOne<"11"> |
        addOne<"12"> | addOne<"13">;

// an elegant solution would be
type numbers = N.Range<'0', '100', '->', 's'>;

type eastimates = TranslateOverArray<numbers, addOne> // 0-1 | 1-2 | 2-3 | 3-4 ....
// output should NOT be like  1-30 | 40-100 etc

```

I think this might not be possible in typescript but a type which takes an array and an another type which is used to translate over that array and the output is not an array rather the output is as either of the resulting array elements;

its like an array takes a random element from array and gives the output. maybe

just for reference String literal types --> [https://www.typescriptlang.org/docs/handbook/literal-types.html#string-literal-types](url)

**Comment by millsp** [comment]
Hey @navanshu, I'm not sure I'm able to write such a type. You should try to write your own recursive type. I'll see if I can solve your use case by writing a `Split` and `Join` types.

**Comment by navanshu** [comment]
I tried again maybe this can help somewhat, this gives the answer not the right one though
```typescript
type addOne<K extends string> = `${K}-${N.Plus<K, '1'>}`;
type test3 = N.Range<'1', '10', '->', 's'>;
type experiment = addOne<test3[number]>; 
```

This shows that typescript can iterate over arrays  but this gives good and bad values maybe after this the split funciton could be used to filter out the bad values that dont conform the result, it needs some work to be done.

**Comment by joseDaKing** [comment]
A split can be written in this way. It will be guaranteed to work.
```ts
type Split<Input extends string, Delimeter extends string = "."> = (
    Input extends `${infer U}${Delimeter}}${infer R}`
    ? [U, ...Split<R>]
    : [Input]
)
```
