### ISSUE TITLE
Error when building since last deploy (9.1.7) 

### ISSUE THREAD

**Issue by morganicx** [millsp/ts-toolbelt#173]
I get a typescript error when building my project since the last deploy: 

```
/node_modules/easy-peasy/node_modules/ts-toolbelt/out/index.d.ts
[INFO] TypeScript error in /builds/.../frontend/node_modules/easy-peasy/node_modules/ts-toolbelt/out/index.d.ts(983,46):
[INFO] Type expected.  TS1110
[INFO] 
[INFO]     981 |     ```
[INFO]     982 |     */
[INFO]   > 983 |     export type NumberOf<N extends number> = `${N}`;
[INFO]         |                                              ^
[INFO]     984 | }
[INFO]     985 | declare module "Any/_Internal" {
[INFO]     986 |     import { NumberOf as NNumberOf } from "Number/NumberOf";
[INFO] 
[INFO] 
```

**Comment by millsp** [comment]
If you can switch to ts >= 4.1 while I provide a fix. It's very hard atm to do this, the release system was broken on these versions. But I'll investigate and publish a sane version manually.

**Comment by millsp** [comment]
Fixing this will cause breaking changes, it's not easy. Because there is global scope pollution. If I fix this, people using global imports will break, if I don't it breaks too - at least only for people that have two different versions of ts-toolbelt at the same time. This has been fixed in version `9`.

**Comment by mesqueeb** [comment]
what does it mean
> people using global imports will break

**Comment by millsp** [comment]
It means that doing imports like `import Merge from "Object/Merge"` would break if I fixed this. This is the reason why it is not allowed no longer in version `9`, it caused module pollution.

**Comment by millsp** [comment]
Closing this as it cannot be backwards-resolved but has been resolved in version 9.
