### ISSUE TITLE
list breaking changes for v9

### ISSUE THREAD

**Issue by mesqueeb** [millsp/ts-toolbelt#175]
I need to consider wether or not to upgrade to v9, but I cannot find the "breaking changes" section in the change log.

Can you clarify it? Thanks!!

<img width="545" alt="image" src="https://user-images.githubusercontent.com/3253920/106537262-55b0e980-653d-11eb-8f38-f654babc65e2.png">

**Comment by millsp** [comment]
This version is especially breaking, it would be hard to tell what has broken.
Core utils like `At` have been changed, and lots of APIs, params have changed.
I'll try to document this, but this goes really DEEP.
