### ISSUE TITLE
Repo Description 👷 Emoji

### ISSUE THREAD

**Issue by buschtoens** [millsp/ts-toolbelt#220]
Thanks for the great project!

While googling I noticed that the current repository description may get displayed weirdly.

> 👷‍♂️ TypeScript's largest utility library 

_becomes, in both Chrome and Firefox:_

![image](https://user-images.githubusercontent.com/834636/110333026-657e8a80-8021-11eb-8c45-3b08bd25b12c.png)

This is because the current repo description uses the male version of the construction worker emoji. You can see that by running:

```ts
'👷‍♂️'.length // => 5
'👷‍♂️'.charAt(3) // => '♂'
```

I suggest that we replace the male version with the gender neutral one:

```ts
'👷'.length // => 2
```

Happy International Women's Day! 🥳

**Comment by millsp** [comment]
Fixed :tada:. Thank you!
