### ISSUE TITLE
Can I get the strict keys for an array somehow? 

### ISSUE THREAD

**Issue by nandorojo** [millsp/ts-toolbelt#254]
## 🍩 Feature Request

I want to get the keys of an array of fixed length, without adding `as const` to the end of the array. I'm able to get the strict values of it, but not the keys.

#### Describe the solution you'd like

I'd like to use a type factory to get the readonly keys of an array:

```ts
import { List } from "ts-toolbelt";

function makeTheme<T>(t: T): T {
  return t;
}
 
const theme = makeTheme({
  space: [1, 2]
});

type Keys = List.StrictKeys<typeof theme['space']> // "0" | "1"
```

#### Describe alternatives you've considered

```ts
import { List } from "ts-toolbelt";

function makeTheme<T>(t: T): T {
  return t;
}

// comment in the 'as const' to solve it 😕
const theme = makeTheme({
  space: [1, 2] // as const
});

type Space = List.CompulsoryKeys<typeof theme["space"]>;

// this should work
const space: Space = "0";

// this should only allow "0" and "1", but it allows any number
const key: keyof typeof theme["space"] = 10;

```

Code: https://codesandbox.io/s/ts-toolbelt-test-forked-89wql?file=/src/index.ts:0-396

#### Screenshots

<img width="721" alt="Screen Shot 2021-09-29 at 3 26 36 PM" src="https://user-images.githubusercontent.com/13172299/135335406-4823bdf4-59b0-4e5c-9856-bff28d8242e5.png">
<img width="724" alt="Screen Shot 2021-09-29 at 3 26 32 PM" src="https://user-images.githubusercontent.com/13172299/135335408-9b2a6374-1b4f-468a-aa23-db156392bfbc.png">
<img width="647" alt="Screen Shot 2021-09-29 at 3 26 27 PM" src="https://user-images.githubusercontent.com/13172299/135335409-ef21fbc5-6b44-4245-a80e-8cc31a6d09fa.png">

Thank you!!

**Comment by tonivj5** [comment]
Hey! @millsp did it some time ago! You can use [`Function.Narrow`](https://github.com/millsp/ts-toolbelt/blob/master/sources/Function/Narrow.ts)

Some context: https://github.com/microsoft/TypeScript/issues/30680#issuecomment-752725353

You can check it working here:
https://codesandbox.io/s/ts-toolbelt-test-forked-hnvml?file=/src/index.ts

**Comment by nandorojo** [comment]
You just made my day.

@millsp what would we do without you?
